apiVersion: v1
kind: PersistentVolume
metadata:
  name: sauth-prod
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sauthdata-prod"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sauth-dev
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sauthdata-dev"
