apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base
patchesStrategicMerge:
- ingress.yaml
configMapGenerator:
- name: landpassauthserver-config
  behavior: merge
  envs:
  - config.env
